locale: en
lang: en

remote_theme: "mmistakes/minimal-mistakes@4.26.2"
minimal_mistakes_skin: "air"

title: "Dr. Ponnavaikko Murugesan"
name: "Dr. Ponnavaikko Murugesan"
description: "Former vice-chancellor of Bharathidasan, SRM, and Bharath universities; founding director of Tamil Virtual University; IEEE India Council chair."
url: "https://ponnavaikko.com"
baseurl: ""

encoding: "utf-8"

author:
  name: "Dr. Ponnavaikko Murugesan"
  avatar: "/images/avatar.jpg"
  bio: "Academic leader and innovator in power systems, Tamil computing, and higher education reform."
  location: "United States"
  links:
    - label: "Autobiography"
      url: "/content/Autobiography.pdf"
    - label: "Résumé (PDF)"
      url: "/content/vcbio.pdf"
    - label: "Publications"
      url: "/publications/"

plugins:
  - jekyll-include-cache
  - jekyll-sitemap
  - jekyll-seo-tag
  - faraday-retry

collections:
  pages:
    output: true
    permalink: /:path/

include:
  - _pages
  - content
  - assets

markdown: kramdown
permalink: pretty
paginate: 0

pagination:
  enabled: false

footer:
  links:
    - label: "Résumé"
      url: "/content/vcbio.pdf"
    - label: "Awards"
      url: "/achievements/#awards-and-honors"
